node {
    stage('Build') {
        docker.image('python:2-alpine').inside('-v /home/dicoding/dev-ops-inter/sub2/simple-python-pyinstaller-app:/source') {
            sh 'ls /'
            sh 'python -m py_compile /source/add2vals.py /source/calc.py'
        }
    }
    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            junit 'test-reports/results.xml'
        }
    }
    stage('Manual Approval') {
        input 'Do you want to deploy?'
    }
    stage('Deploy') {
        try {
            sh 'docker run -v "$(pwd)/sources:/src/" cdrx/pyinstaller-linux:python2 "pyinstaller --onefile /src/add2vals.py"'
            archiveArtifacts 'sources/dist/add2vals'
        } catch(Exception e) {
            echo e.toString()
        } finally {
            sh 'docker run -v "$(pwd)/sources:/src/" cdrx/pyinstaller-linux:python2 "rm -rf build dist"'
            sleep 60
        }
    }
}
